-- Mock Data for Devices Table
-- This script creates sample devices with various statuses to demonstrate the warehouse management system
-- Note: shipment_id is set to NULL since we don't have shipments created yet

-- Insert mock devices with different statuses
INSERT INTO devices (
    asset_id,
    status,
    model,
    serial_number,
    manufacturer,
    ram_size,
    ram_count,
    ram_models,
    storage_size,
    storage_count,
    storage_types,
    storage_models,
    gpu_model,
    cpu_model,
    current_location,
    created_at,
    updated_at
) VALUES
-- Devices in Inspection (في الفحص)
(
    'AST-001',
    'pending_inspection',
    'Dell Latitude 5420',
    'DL5420-SN001',
    'Dell',
    8,
    2,
    ARRAY['Samsung DDR4'],
    512,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO'],
    'Intel Iris Xe Graphics',
    'Intel Core i7-1165G7',
    'المخزن الرئيسي - منطقة الفحص',
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '2 days'
),
(
    'AST-002',
    'in_physical_inspection',
    'HP EliteBook 840 G8',
    'HP840-SN002',
    'HP',
    16,
    2,
    ARRAY['Crucial DDR4'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['WD Black SN750'],
    'Intel Iris Xe Graphics',
    'Intel Core i7-1185G7',
    'المخزن الرئيسي - منطقة الفحص',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day'
),
(
    'AST-003',
    'in_technical_inspection',
    'Lenovo ThinkPad X1 Carbon Gen 9',
    'LNV-X1C9-SN003',
    'Lenovo',
    16,
    2,
    ARRAY['Samsung DDR4'],
    512,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung PM9A1'],
    'Intel Iris Xe Graphics',
    'Intel Core i7-1185G7',
    'المخزن الرئيسي - منطقة الفحص الفني',
    NOW() - INTERVAL '3 hours',
    NOW() - INTERVAL '3 hours'
),

-- Devices in Warehouse (في المخزن)
(
    'AST-004',
    'received',
    'Dell XPS 15 9510',
    'DXPS15-SN004',
    'Dell',
    32,
    2,
    ARRAY['Corsair DDR4'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO'],
    'NVIDIA GeForce RTX 3050 Ti',
    'Intel Core i7-11800H',
    'المخزن الرئيسي - الرف A-12',
    NOW() - INTERVAL '5 hours',
    NOW() - INTERVAL '5 hours'
),
(
    'AST-005',
    'received',
    'MacBook Pro 14" M1 Pro',
    'MBP14-SN005',
    'Apple',
    16,
    1,
    ARRAY['Apple Unified Memory'],
    512,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Apple SSD'],
    'Apple M1 Pro 16-core GPU',
    'Apple M1 Pro 10-core CPU',
    'المخزن الرئيسي - الرف B-05',
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '6 hours'
),

-- Devices in Maintenance (في الصيانة)
(
    'AST-006',
    'needs_repair',
    'ASUS ROG Zephyrus G14',
    'ASUS-G14-SN006',
    'ASUS',
    16,
    2,
    ARRAY['G.Skill DDR4'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 970 EVO Plus'],
    'NVIDIA GeForce RTX 3060',
    'AMD Ryzen 9 5900HS',
    'ورشة الصيانة - قسم التشخيص',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day'
),
(
    'AST-007',
    'in_repair',
    'MSI GE76 Raider',
    'MSI-GE76-SN007',
    'MSI',
    32,
    2,
    ARRAY['Kingston DDR4'],
    2048,
    2,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO', 'WD Black SN850'],
    'NVIDIA GeForce RTX 3070',
    'Intel Core i7-11800H',
    'ورشة الصيانة - طاولة العمل 3',
    NOW() - INTERVAL '12 hours',
    NOW() - INTERVAL '12 hours'
),

-- Devices Ready for Sale (جاهز للبيع)
(
    'AST-008',
    'ready_for_sale',
    'Dell Precision 5560',
    'DP5560-SN008',
    'Dell',
    32,
    2,
    ARRAY['Crucial DDR4'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung PM9A1'],
    'NVIDIA Quadro T1200',
    'Intel Core i7-11850H',
    'المخزن الرئيسي - منطقة الجاهز للبيع',
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '2 days'
),
(
    'AST-009',
    'ready_for_sale',
    'HP ZBook Studio G8',
    'HP-ZBS-SN009',
    'HP',
    32,
    2,
    ARRAY['Samsung DDR4'],
    2048,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO'],
    'NVIDIA RTX A2000',
    'Intel Core i9-11950H',
    'المخزن الرئيسي - منطقة الجاهز للبيع',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '1 day'
),
(
    'AST-010',
    'ready_for_sale',
    'Lenovo ThinkPad P15 Gen 2',
    'LNV-P15-SN010',
    'Lenovo',
    64,
    4,
    ARRAY['Crucial DDR4'],
    2048,
    2,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO', 'WD Black SN850'],
    'NVIDIA RTX A4000',
    'Intel Core i9-11950H',
    'المخزن الرئيسي - منطقة الجاهز للبيع',
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '3 days'
),

-- Additional devices with various statuses
(
    'AST-011',
    'pending_inspection',
    'Acer Predator Helios 300',
    'ACER-PH300-SN011',
    'Acer',
    16,
    2,
    ARRAY['HyperX DDR4'],
    512,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['WD Black SN750'],
    'NVIDIA GeForce RTX 3060',
    'Intel Core i7-11800H',
    'المخزن الرئيسي - منطقة الفحص',
    NOW() - INTERVAL '4 hours',
    NOW() - INTERVAL '4 hours'
),
(
    'AST-012',
    'received',
    'Razer Blade 15',
    'RZR-B15-SN012',
    'Razer',
    16,
    2,
    ARRAY['Samsung DDR4'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 970 EVO Plus'],
    'NVIDIA GeForce RTX 3070',
    'Intel Core i7-11800H',
    'المخزن الرئيسي - الرف C-08',
    NOW() - INTERVAL '8 hours',
    NOW() - INTERVAL '8 hours'
),
(
    'AST-013',
    'in_repair',
    'Gigabyte AERO 15',
    'GB-AERO15-SN013',
    'Gigabyte',
    32,
    2,
    ARRAY['G.Skill DDR4'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO'],
    'NVIDIA GeForce RTX 3070',
    'Intel Core i7-11800H',
    'ورشة الصيانة - طاولة العمل 1',
    NOW() - INTERVAL '18 hours',
    NOW() - INTERVAL '18 hours'
),
(
    'AST-014',
    'ready_for_sale',
    'Microsoft Surface Laptop Studio',
    'MS-SLS-SN014',
    'Microsoft',
    32,
    1,
    ARRAY['Samsung LPDDR4x'],
    1024,
    1,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung PM9A1'],
    'NVIDIA GeForce RTX 3050 Ti',
    'Intel Core i7-11370H',
    'المخزن الرئيسي - منطقة الجاهز للبيع',
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '4 days'
),
(
    'AST-015',
    'in_physical_inspection',
    'Alienware m15 R6',
    'ALW-M15-SN015',
    'Dell',
    32,
    2,
    ARRAY['Kingston DDR4'],
    2048,
    2,
    ARRAY['NVMe SSD'],
    ARRAY['Samsung 980 PRO', 'WD Black SN850'],
    'NVIDIA GeForce RTX 3080',
    'Intel Core i9-11900H',
    'المخزن الرئيسي - منطقة الفحص',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '2 hours'
);

-- Verify the inserted data
SELECT 
    status,
    COUNT(*) as count
FROM devices
GROUP BY status
ORDER BY status;

-- Show sample of inserted devices
SELECT 
    asset_id,
    model,
    manufacturer,
    status,
    current_location
FROM devices
WHERE asset_id LIKE 'AST-%'
ORDER BY asset_id
LIMIT 5;
